### ISSUE TITLE
[BUG] Error popup on start

### ISSUE THREAD

**Issue by MrAltF4** [ho0ber/NK2Tray#110]
**Describe the bug**
When launching the EXE an error appears. This has only started to happen in the past week, i wonder if this is something to do with a windows update? Nothing else has change don my machine.

**To Reproduce**
1. Go to 'NK2Tray.exe' and launch it
2. See error

**Expected behavior**
Normally there's no issues and the app launches allowing the MIDI to control all the audio channels.

**Screenshots**
![image](https://user-images.githubusercontent.com/47820949/164978008-c23fffa5-6613-4feb-97d8-b9a2f95b205b.png)

**Desktop (please complete the following information):**
 - OS: 20H2
 - OS Build: 19042.1645
 - Version 0.0.16.0

**Midi device:**
 - Korg NanoKONTROL2

**Additional context**
I've been using this software for over 2 years, maybe more. Thank you.

Thanks so much for making this software. i can see that the app isn't active, which is a shame, because this is the only reason I bought this MIDI device. You've done us all a great favour making this app. I plead for your to continue development, or at the least see if we can solve why it's started creating errors.

**Comment by ho0ber** [comment]
Hey @MrAltF4 - thanks for your kind words. Admittedly, exactly this kind of error is part of why I haven't tried to continue development of NK2Tray itself. I would love for developers with a more active interest and/or experience in native windows app development to pick it up, but that isn't my personal strength.

Because I still care about having a free and open-source solution to meet this need, I've actually started another rewrite from scratch called [Havomi](https://github.com/ho0ber/havomi), which is written in python, a language and ecosystem I'm significantly more comfortable with, and which should allow me to provide support indefinitely without significant time investment. The rewrite is slow-going, but it is functional in its current state. I encourage you to join the discord to follow along if you're interested.

But if you're just looking for a working solution, a contributor to NK2Tray wrote a very polished alternative that is definitely worth checking out: [Midi Mixer](https://www.midi-mixer.com/). It's not as dead-simple as NK2Tray and it's not open source, but in basically every other way it is superior to my project(s).

**Comment by MrAltF4** [comment]
> Hey @MrAltF4 - thanks for your kind words. Admittedly, exactly this kind of error is part of why I haven't tried to continue development of NK2Tray itself. I would love for developers with a more active interest and/or experience in native windows app development to pick it up, but that isn't my personal strength.
> 
> Because I still care about having a free and open-source solution to meet this need, I've actually started another rewrite from scratch called [Havomi](https://github.com/ho0ber/havomi), which is written in python, a language and ecosystem I'm significantly more comfortable with, and which should allow me to provide support indefinitely without significant time investment. The rewrite is slow-going, but it is functional in its current state. I encourage you to join the discord to follow along if you're interested.
> 
> But if you're just looking for a working solution, a contributor to NK2Tray wrote a very polished alternative that is definitely worth checking out: [Midi Mixer](https://www.midi-mixer.com/). It's not as dead-simple as NK2Tray and it's not open source, but in basically every other way it is superior to my project(s).

Thanks @ho0ber for getting back to me. I managed to fix it. I'm not 100% sure how, but in looking for an alternative, i installed a couple of programs (one of which was your new version of this "Havomi") and another which was something called Midi Manager, which i found on your discord.

Then in showing a friend how yours wasn't working... it suddenly worked again. 
All i can think is that one of those two exes somehow fixed whatever the issues were for me.
I hope that this works for someone else out there.

Again, I appreciate you restarting the project, I can understand your reasoning.
It's a great and super easy user experience.

Keep it up :)
